apiVersion: v1
kind: Service
metadata:
  name: kafka
spec:
  selector:
    app: kafka
  ports:
    - name: kafka
      port: 9092
      targetPort: 9092
      nodePort: 32092
    - name: zookeper
      port: 2181
      targetPort: 2181
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kafka
spec:
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: spotify/kafka:latest
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 100m
              memory: 512Mi
          ports:
            - name: kafka
              containerPort: 9092
            - name: zookeper
              containerPort: 2181